# Generated by Django 5.1.2 on 2024-11-12 01:17

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from products.models import Product

def create_groups(apps, schema_editor):
    # Criar grupo de administradores
    admin_group = Group.objects.create(name='Administradores')
    
    # Criar grupo de usuários normais
    user_group = Group.objects.create(name='Usuarios')
    
    # Obter content type do modelo Product
    product_content_type = ContentType.objects.get_for_model(Product)
    
    # Definir permissões para produtos
    add_product = Permission.objects.get(
        content_type=product_content_type,
        codename='add_product'
    )
    delete_product = Permission.objects.get(
        content_type=product_content_type,
        codename='delete_product'
    )
    
    # Adicionar permissões aos grupos
    admin_group.permissions.add(delete_product)  # Admins podem deletar
    user_group.permissions.add(add_product)      # Usuários podem adicionar

def remove_groups(apps, schema_editor):
    # Função para reverter as mudanças se necessário
    Group.objects.filter(name__in=['Administradores', 'Usuarios']).delete()

class Migration(migrations.Migration):
    dependencies = [
        # Remova as dependências se não forem necessárias
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
