# Generated by Django 5.1.2 on 2024-11-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado'), ('em_manutencao', 'Em Manutenção'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20),
        ),
    ]
